# Generated by Django 3.1.11 on 2021-05-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('INTERNSHIP', 'Internship'), ('PLACEMENT', 'Placement')], default='PLACEMENT', max_length=12),
        ),
    ]
