# Generated by Django 3.1.11 on 2021-06-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_shortlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='number',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Final')], default=1),
        ),
    ]
