# Generated by Django 3.1.11 on 2021-06-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_apply_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jd',
            field=models.FileField(null=True, upload_to='jd/pdf'),
        ),
    ]
