# Generated by Django 3.2.5 on 2021-07-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210705_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jd',
            field=models.FileField(max_length=1000, null=True, upload_to='jd/pdf'),
        ),
    ]
