# Generated by Django 3.1.11 on 2021-05-30 08:11

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('personal_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_no', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('roll_no', models.CharField(default='', max_length=8)),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('dob', models.DateField(max_length=8)),
                ('department', models.CharField(default='', max_length=2)),
                ('category', models.PositiveIntegerField(choices=[(1, 'General'), (2, 'SC'), (3, 'ST'), (4, 'OBC'), (5, 'OTHERS')], default=1)),
                ('hometown', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('percentage_ten', models.FloatField(blank=True, default=0, null=True)),
                ('percentage_twelve', models.FloatField(blank=True, default=0, null=True)),
                ('cgpa_s1', models.FloatField(blank=True, default=0, null=True)),
                ('cgpa_s2', models.FloatField(blank=True, default=0, null=True)),
                ('cgpa_s3', models.FloatField(blank=True, default=0, null=True)),
                ('cgpa_s4', models.FloatField(blank=True, default=0, null=True)),
                ('cgpa_s5', models.FloatField(blank=True, default=0, null=True)),
                ('cgpa_s6', models.FloatField(blank=True, default=0, null=True)),
                ('cgpa_s7', models.FloatField(blank=True, default=0, null=True)),
                ('cgpa_s8', models.FloatField(blank=True, default=0, null=True)),
                ('is_coordinator', models.BooleanField(default=False)),
                ('graduation_year', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
