# Generated by Django 3.1.11 on 2021-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210530_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
        migrations.AddField(
            model_name='student',
            name='resume_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
