# Generated by Django 3.1.11 on 2021-06-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210624_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cur_backlog',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_loc',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_backlogs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
